server:
  port: 1050
eureka:
  client:
    serviceUrl: #指向Eureka服务端地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 2 #服务发现的间隔时间
  instance:
    prefer-ip-address: true #开启用IP注册
    instance-id: service-auth:1050 #自定义实例ID

spring:
  #seata相关配置
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group #这里和file.conf中事务组名一样
  #配置数据库链接信息
  datasource:
    url: jdbc:mysql:///hrm-auth
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: service-auth #服务名

mybatis-plus: #集成MyBatis-Plus
  mapper-locations: classpath:cn/itsource/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰大小写自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台sql输出

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: 3 #最大重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 5000 #请求处理的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #hystrix超时,置thread和semaphore两种隔离策略的超时时间
